[project]
name = "minicrm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "databases[sqlite]>=0.9.0",
    "fastapi[all]>=0.115.11",
    "sqlmodel>=0.0.23",
]
